package com.Exception;

import java.util.Arrays;

public class Main {

    public static void main(String[] args) {
        Stack s = new Stack(5);
        try{
            s.push(1);
            s.push(3);s.push(1);
            s.push(3);
            s.push(3);
            s.push(3);
            try{
                s.pop();
            }
            catch (Underflow e){
                System.out.println(e);
            }
        }
        catch (Overflow e){
            System.out.println(e);
        }

    }
}

 class Stack {
     private int top = -1;
     private int arr[];
     private int size;

     Stack(int size) {
          this.size=size;
         arr = new int[size];

     }

     public void push(int x) throws Overflow {
         if (top == size - 1)
             throw new Overflow();
         top++;
         arr[top] = x;
     }

     public int pop() throws Underflow{
         int x = 0;
         if (top == -1)
             throw new Underflow();
         x = arr[top];
         top--;
         return x;

     }
 }
    class Overflow extends Exception{
         public String toString(){
             return "Stackoverflow";
         }
    }
    class Underflow extends Exception{
         public String toString(){
             return "Stackunderflow";
         }

    }
